// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj9R91WZJeJmS91uVW-Kr0x16c6vXKIYU',
    appId: '1:441133021852:web:ab970acf02c3c1f683cb59',
    messagingSenderId: '441133021852',
    projectId: 'foodautomation-1a2f8',
    authDomain: 'foodautomation-1a2f8.firebaseapp.com',
    storageBucket: 'foodautomation-1a2f8.firebasestorage.app',
    measurementId: 'G-WLH7P21T65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjjc875pE34DyHsKbIn6m66xCPhMfpbE',
    appId: '1:441133021852:android:ed742413761aebb283cb59',
    messagingSenderId: '441133021852',
    projectId: 'foodautomation-1a2f8',
    storageBucket: 'foodautomation-1a2f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXc0Ffca9GAyS5nMlY0i6Vw8nN4LKfr8',
    appId: '1:441133021852:ios:b41e9fe6e38b64e583cb59',
    messagingSenderId: '441133021852',
    projectId: 'foodautomation-1a2f8',
    storageBucket: 'foodautomation-1a2f8.firebasestorage.app',
    iosBundleId: 'com.example.dndPrttp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXXc0Ffca9GAyS5nMlY0i6Vw8nN4LKfr8',
    appId: '1:441133021852:ios:882e90c272bcea4383cb59',
    messagingSenderId: '441133021852',
    projectId: 'foodautomation-1a2f8',
    storageBucket: 'foodautomation-1a2f8.firebasestorage.app',
    iosBundleId: 'com.example.dndPrttp.RunnerTests',
  );
}
